### ISSUE TITLE
cookie不知道怎么获取

### ISSUE THREAD

**Issue by llxlr** [mxnter/TerBiliLive#1]
一脸懵

**Comment by llxlr** [comment]
![image](https://user-images.githubusercontent.com/33483752/51843121-5494c280-234d-11e9-8f01-29b696757b4e.png)
？？？

**Comment by mxnter** [comment]
F12 >Network > 随意找一个请求 > Headers >里面会有Cookie 的

**Comment by mxnter** [comment]
![66666666](https://user-images.githubusercontent.com/36059946/52037523-3c4dbf00-256a-11e9-9f31-ccce8e19322d.jpg)
